### ISSUE TITLE
Sanitize all inputs via js

### ISSUE THREAD

**Issue by DamSenViet** [Thulinma/ACNLPatternTool#11]
https://discordapp.com/channels/522493551288909834/691957767677673513/694461685565489233

Users should not be allowed to modify character limits. (not sure if this is already checked in the backend). Need to sanitize all user inputs in js rather than just html.

**Comment by Thulinma** [comment]
This happens already - the input is trimmed to 9 chars in the JS library and more than 9 chars cannot make it into the storage format at all. Backend receives the raw storage format + tags only, so there's nothing to fix here. ^_^

**Comment by DamSenViet** [comment]
im a big dumb
