### ISSUE TITLE
Doesn't run in Safari

### ISSUE THREAD

**Issue by ryanmcgrath** [Thulinma/ACNLPatternTool#4]
You likely need a `BigInt` polyfill, as Safari doesn't support it. Are you sure this works on iOS Safari?

https://github.com/graup/bigint-polyfill

**Comment by Thulinma** [comment]
Thanks, very helpful! We haven't tested Safari since we started using BigInt, so it suddenly all makes sense why the /browse page is broken in Safari... Will add the polyfill soon!

**Comment by DamSenViet** [comment]
I've finished patching the polyfill. Babel's polyfill for bigInt is still in its proposal stages for the past year or so.

https://github.com/GoogleChromeLabs/jsbi
