### ISSUE TITLE
Error loading the gltf file

### ISSUE THREAD

**Issue by ydzhang12345** [Thulinma/ACNLPatternTool#42]
I am running in win10. When I try to build the project, it throws the following errors:

ERROR in ./injected/easel/model.gltf 2:12
Module parse failed: Unexpected token (2:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| {
>     "asset" : {
|         "version" : "2.0",
|         "generator" : "Khronos glTF Blender I/O v1.2.20"

any idea how to fix it? I tried google around but with no luck. Many thanks!

**Comment by DamSenViet** [comment]
We have a generic loader to hande this no?
https://github.com/Thulinma/ACNLPatternTool/blob/master/config/webpack.config.js#L233

**Comment by ydzhang12345** [comment]
Thank you for your reply.  Does the project require some specific package versions?

**Comment by DamSenViet** [comment]
You should be using the pinned node version under .nvm or you may end up installing the wrong packages.

My recommendation is to use nvm (node version manager)  this a common tool for multi-project management.
