### ISSUE TITLE
Question about New Horizons Colors.

### ISSUE THREAD

**Issue by kylepaulsen** [Thulinma/ACNLPatternTool#5]
I'm not sure, but I think new horizons has more colors than new leaf available in the pro editor.

If so, are there plans to allow this tool to use those colors?
If not, do you know if there is another tool for new horizons?

I might consider getting involved if my motivation picks up. Nice Vue app by the way.

Edit: I might have just discovered that new horizons doesnt give you QR codes anymore. Is this true? If so, then I guess we can't add the new colors.

**Comment by Thulinma** [comment]
Hi! Correct, ACNH has more colors, and correct, it never gives out QR codes.
The new colors can not be used through QR code conversion - but it is possible to inject them directly into savegames (which we'll be supporting soon!).
For reference: ACNL uses a limited < 8-bit palette (1 byte, but many values are unused/undefined, so it's less than 8-bit). ACNH uses/stores full 24-bit RGB internally, but the interface in-game limits you to < 16 bits of color precision. Interestingly: only some of the ACNL colors are pickable in the ACNH interface! This means the conversions through QR codes can access some colors that you cannot normally access through other in-game means.

**Comment by megaroeny** [comment]
Isn't it possible to share QR codes now via the Nintendo Online mobile app? Or no. I don't have the game yet, but planning on buying it this week and got curious about the designer. Then came across your website. 🙂

I saw someone in Twitter mention this:

> I’m pretty sure you need to wait for the Able Sisters shop to open in New Horizons before you can generate a QR code. Then (& I’m guessing here), Sable will have a sewing machine like she had in New Leaf where you could create QR codes & save to your Album, then share to Twitter!

Any idea if this will be compatible with what you're trying to do with this app still?

**Comment by Thulinma** [comment]
@megaroeny
You can indeed scan ACNL-based QR codes into ACNH (which is what the website generates!)
The Able Sisters shop generates ID codes now that are stored on Nintendo's servers. Trying to write to that is like asking Nintendo for a ban, so that's not going to happen.
We can write directly to savegames (support coming soon!), but that requires a modded Switch.

**Comment by megaroeny** [comment]
> @megaroeny
> You can indeed scan ACNL-based QR codes into ACNH (which is what the website generates!)
> The Able Sisters shop generates ID codes now that are stored on Nintendo's servers. Trying to write to that is like asking Nintendo for a ban, so that's not going to happen.
> We can write directly to savegames (support coming soon!), but that requires a modded Switch.

Got it! Yeah don't want you getting in trouble like that lol! Well I appreciate this app you've made. I'll have fun trying out both methods. Thanks!

**Comment by merlinpatt** [comment]
Does the closure of this issue mean that New Horizons colors have been added to the tool?

**Comment by DamSenViet** [comment]
For the ACNH portion of our App yes, we've added an ACNH color picker.
